version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
      - VITE_N8N_WEBHOOK_URL=${VITE_N8N_WEBHOOK_URL}
      - VITE_USE_REAL_CHAT=${VITE_USE_REAL_CHAT}
    depends_on:
      - backend
    networks:
      - ragchat-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads-data:/app/uploads
    environment:
      - NODE_ENV=development
      - PORT=3001
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
      - GOOGLE_CLIENT_EMAIL=${GOOGLE_CLIENT_EMAIL}
      - GOOGLE_PRIVATE_KEY=${GOOGLE_PRIVATE_KEY}
    networks:
      - ragchat-network

volumes:
  uploads-data:
    driver: local

networks:
  ragchat-network:
    driver: bridge